export default {
    //clientInfo-根据用户id查询用户详细信息
    clientInfoById: {
        "createTime": "2019-07-23 10:25:09",
        "createUserId": "0",
        "createUserName": "",
        "updateTime": "2019-07-23 10:25:09",
        "updateUserId": "0",
        "updateUserName": "",
        "deleteFlag": 1,
        "userCache": null,
        "commodityCode": null,
        "id": "1",
        "cid": "2",
        "memberSn": "ydsc000001",
        "headIcon": "https://www.weixin.com",
        "nickName": "德玛西亚",
        "phone": "18701443234",
        "memberType": 1,
        "channelId": "1",
        "channelName": "微信",
        "status": 0,
        "memberName": "李四",
        "sex": 1,
        "birthday": "2019-07-16 10:23:45",
        "wechatSn": "1111111",
        "email": "1789876536@qq.com",
        "provinceCode": "110000",
        "provinceName": "北京",
        "cityCode": "110101",
        "cityName": "东城区",
        "areaCode": "110101",
        "areaName": "东城区",
        "address": "东城区西直门大街10001号",
        "becameCustomerTime": "2019-07-03 10:24:36",
        "becameMemberTime": "2019-07-11 10:24:40",
        "levelInfoId": "1",
        "levelName": "vip1",
        "cardLevelInfoId": null,
        "cardLevelName": "金卡",
        "couponNum": 5,
        "score": 100,
        "balance": 50,
        "frozenBalance": null,
        "dealTimes": 2,
        "totalDealMoney": 200,
        "perUnitPrice": 100,
        "lastPayTime": "2019-07-16 10:25:03"
    },
    //allClient-查询客户列表
    allUserList: [
        {
            "createTime": "2019-07-23 10:25:09",
			"createUserId": "0",
			"createUserName": "",
			"updateTime": "2019-07-23 10:25:09",
			"updateUserId": "0",
			"updateUserName": "",
			"deleteFlag": 1,
			"userCache": null,
			"commodityCode": null,
			"id": "1",
			"cid": "2",
			"memberSn": "ydsc000001",
			"headIcon": "https://www.weixin.com",
			"nickName": "德玛西亚",
			"phone": "18701443234",
			"memberType": 1,
			"channelId": "1",
			"channelName": "微信",
			"status": 0,
			"memberName": "李四",
			"sex": 1,
			"birthday": "2019-07-16 10:23:45",
			"wechatSn": "1111111",
			"email": "1789876536@qq.com",
			"provinceCode": "110000",
			"provinceName": "北京",
			"cityCode": "110101",
			"cityName": "东城区",
			"areaCode": "110101",
			"areaName": "东城区",
			"address": "东城区西直门大街10001号",
			"becameCustomerTime": "2019-07-03 10:24:36",
			"becameMemberTime": "2019-07-11 10:24:40",
			"levelInfoId": "1",
			"levelName": "vip1",
			"cardLevelInfoId": null,
			"cardLevelName": "",
			"score": 100,
			"balance": 50,
			"frozenBalance": null,
			"dealTimes": 2,
			"totalDealMoney": 200,
			"perUnitPrice": 100,
			"lastPayTime": "2019-07-16 10:25:03"
        },
        {
            "createTime": "2019-07-23 10:25:09",
			"createUserId": "0",
			"createUserName": "",
			"updateTime": "2019-07-23 10:25:09",
			"updateUserId": "0",
			"updateUserName": "",
			"deleteFlag": 1,
			"userCache": null,
			"commodityCode": null,
			"id": "1",
			"cid": "2",
			"memberSn": "ydsc000002",
			"headIcon": "https://www.weixin.com",
			"nickName": "德玛西亚2",
			"phone": "18701443234",
			"memberType": 1,
			"channelId": "1",
			"channelName": "微信",
			"status": 2,
			"memberName": "李四",
			"sex": 1,
			"birthday": "2019-07-16 10:23:45",
			"wechatSn": "1111111",
			"email": "1789876536@qq.com",
			"provinceCode": "110000",
			"provinceName": "北京",
			"cityCode": "110101",
			"cityName": "东城区",
			"areaCode": "110101",
			"areaName": "东城区",
			"address": "东城区西直门大街10001号",
			"becameCustomerTime": "2019-07-03 10:24:36",
			"becameMemberTime": "2019-07-11 10:24:40",
			"levelInfoId": "1",
			"levelName": "vip1",
			"cardLevelInfoId": null,
			"cardLevelName": "",
			"score": 100,
			"balance": 50,
			"frozenBalance": null,
			"dealTimes": 2,
			"totalDealMoney": 200,
			"perUnitPrice": 100,
			"lastPayTime": "2019-07-16 10:25:03"
        }
    ],
    //allClient-查询所有标签
    tagData: [
        {
            "id": "1",
            "cid": "2",
            "tagName": "新青年",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"消费满100"
        },
        {
            "id": "2",
            "cid": "2",
            "tagName": "女强人",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"消费满100"
        },
        {
            "id": "3",
            "cid": "2",
            "tagName": "爱旅游",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"消费满100"
        },
        {
            "id": "4",
            "cid": "2",
            "tagName": "爱看书",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"消费满100"
        },
        {
            "id": "5",
            "cid": "2",
            "tagName": "多字多字多字",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"消费满100"
        },
        {
            "id": "6",
            "cid": "2",
            "tagName": "somethingsomething",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"消费满100"
        }
    ],
    //根据标签id和商户id查询用户所属标签
    tagsById: [
        {
            "id": "1",
            "cid": "2",
            "tagName": "年轻用户",
            "tagType": 0,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"积分满400"
        },
        {
            "id": "2",
            "cid": "2",
            "tagName": "女性用户",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"积分满400"
        },
        {
            "id": "3",
            "cid": "2",
            "tagName": "卡哇伊",
            "tagType": 0,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"积分满400"
        }
    ],
    //clientImport-客户渠道下拉
    channelOptions: [
        {
            id: '01',
            cid: '001',
            channerlName: '渠道1'
        },
        {
            id: '02',
            cid: '002',
            channerlName: '渠道2'
        }
    ],
    //clientImport-导入记录列表
    channelList: [
        {
			"createTime": "2019-07-25 10:04:33",
			"createUserId": "0",
			"createUserName": "",
			"updateTime": "2019-07-25 10:04:33",
			"updateUserId": "0",
			"updateUserName": "",
			"deleteFlag": 1,
			"userCache": null,
			"commodityCode": null,
			"id": "1",
			"cid": "2",
			"importTime": "2019-07-24 10:03:54",
			"channelId": "1",
			"channerlName": "公众号",
			"totalNum": 10,
			"successNum": 10,
			"failNum": 0,
			"operatorId": "1"
        },
        {
			"createTime": "2019-07-25 10:04:33",
			"createUserId": "1",
			"createUserName": "",
			"updateTime": "2019-07-25 10:04:33",
			"updateUserId": "0",
			"updateUserName": "",
			"deleteFlag": 1,
			"userCache": null,
			"commodityCode": null,
			"id": "1",
			"cid": "2",
			"importTime": "2019-07-24 10:03:54",
			"channelId": "1",
			"channerlName": "微信",
			"totalNum": 30,
			"successNum": 20,
			"failNum": 0,
			"operatorId": "1"
		}
    ],
    //clientLabel-标签列表
    tagList: [
        {
            "startIndex": 1,
            "pageSize": 10,
            "orderBy": null,
            "createTime": null,
            "createUserId": null,
            "createUserName": null,
            "updateTime": null,
            "updateUserId": null,
            "updateUserName": null,
            "deleteFlag": null,
            "userCache": null,
            "id": "1",
            "cid": "2",
            "cid": "2",
            "tagName": "标签名",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"标签条件描述",
            "labelContains": 100
        },
        {
            "startIndex": 1,
            "pageSize": 10,
            "orderBy": null,
            "createTime": null,
            "createUserId": null,
            "createUserName": null,
            "updateTime": null,
            "updateUserId": null,
            "updateUserName": null,
            "deleteFlag": null,
            "userCache": null,
            "id": "1",
            "cid": "2",
            "cid": "2",
            "tagName": "标签名2",
            "tagType": 1,
            "anyOrAllCondition": 1,
            "isLastConsumeTime": 1,
            "consumeTimeType": 0,
            "consumeTimeValue": 12,
            "consumeTimeUnit": 1,
            "consumeTimeStart": 1,
            "consumeTimeEnd": 1,
            "isTotalConsumeTimes": 1,
            "consumeTimesMin": 1,
            "consumeTimesMax": 10,
            "isTotalConsumeMoney": 1,
            "consumeMoneyMin": 5,
            "consumeMoneyMax": 20,
            "isPreUnitPrice": 1,
            "preUnitPriceMin": 10,
            "preUnitPriceMax": 10,
            "isTotalScore": 1,
            "totalScoreMin": 10,
            "totalScoreMax": 2,
            "productInfoIds": "123123,123123",
            "isProduct": 1,
            "enable": 2,
            "labelCondition":"标签条件描述",
            "labelContains": 20
        }
    ],
    //clientLevel-等级列表
    levelList: [
        {
            "startIndex": 1,
            "pageSize": 10,
            "orderBy": null,
            "createTime": null,
            "createUserId": null,
            "createUserName": null,
            "updateTime": null,
            "updateUserId": null,
            "updateUserName": null,
            "deleteFlag": null,
            "userCache": null,
            "id": "1",
            "cid": "2",
            "name": "等级一",
            "levelImageUrl": "http://wwerer.image",
            "alias": "vip1",
            "level": 1,
            "explain": "等级说明",
            "upgradePackage": "升级礼包描述",
            "status": 1,
            "receiveConditionsRemarks": "领取条件描述",
            "rights": "权益描述",
            "type": 1,
            "levelConditionId": 123123,
            "conditionValue": 2,
            "rightsInfoId": 34123123,
            "rightsValue": 12,
            "upgradeRewardInfoId": 123123123,
            "giftProduct": 123123,
            "giftNumber": 1
        },
        {
            "startIndex": 1,
            "pageSize": 10,
            "orderBy": null,
            "createTime": null,
            "createUserId": null,
            "createUserName": null,
            "updateTime": null,
            "updateUserId": null,
            "updateUserName": null,
            "deleteFlag": null,
            "userCache": null,
            "id": "2",
            "cid": "2",
            "name": "等级二",
            "levelImageUrl": "http://wwerer.image",
            "alias": "vip1",
            "level": 1,
            "explain": "等级说明",
            "upgradePackage": "升级礼包描述",
            "status": 1,
            "receiveConditionsRemarks": "领取条件描述",
            "rights": "权益描述",
            "type": 1,
            "levelConditionId": 123123,
            "conditionValue": 2,
            "rightsInfoId": 34123123,
            "rightsValue": 12,
            "upgradeRewardInfoId": 123123123,
            "giftProduct": 123123,
            "giftNumber": 1
        }
    ],
    //creditManage-积分列表
    creditList: [
        {
            sceneName: '登录',
            status: '启用'
        },
        {
            sceneName: '购买商品',
            status: '启用'
        },
        {
            sceneName: '复购商品',
            status: '启用'
        },
        {
            sceneName: '评价',
            status: '启用'
        },
        {
            sceneName: '签到',
            status: '启用'
        }
    ]
}